[Review] 프로필 정보 창 수정 및 화상 채팅방 반응형 CSS 수정
boostcampwm-2021/web12-sooltreaming pull request #167
Opened 2021-11-26 10:07 UTC by jyo-jyo

### WorkList

- [x] ✨ 닉네임 & 프로필 사진 변경하는 모달 
- [x] ✨ Multer를 이용해 이미지 받기 & 유저 정보 변경 로직 작성 
- [x] 🐛 이미지 전송을 위해 FormData 사용으로 인해 custom Fetch를 사용하지 못하던 버그 수정
- [x] ✨ crontab을 이용해서 랭크 정렬 작업!!! 
- [x] ✨ 클라이언트 귀여운 에러 토스트 메시지 
- [x] 💄 카메라 화면 유사 반응형 ^_^ 

### Issue

- 늦은 리뷰 신청이 이슈입니다.

### Description

저희가 너무 바빠서 어쩌다 보니 분량이 너무 늘어나서 리뷰를 PR 단위로 못했습니다..
그래서 리뷰 받고 싶은 파일, 기능만 속속 빼와서 리뷰를 신청합니다...!
이번주도 너무너무 고생 많으셨습니다!!!

2021-11-26 13:50 UTC, SeojinSeojin reviewed
로직이 너무나 깔끔하시고 주석도 잘 달려있어서 이해하고 코드 읽는데에 한층 수월했습니다!!

큰 구조와 흐름보다는 자잘한 요소만 짚게 되었는데요 ... 조금이라도 도움이 되었으면 좋겠습니다!!

2021-11-26 13:50 UTC, SeojinSeojin commented on client/src/api/index.ts
> +import { store } from '@src/store/store';
이 친구도 `@store` 출신일 것 같습니다!

2021-11-26 13:50 UTC, SeojinSeojin commented on client/src/components/room/monitor/index.style.ts
> +  ${(props) => {
우와 👍👍👍

2021-11-26 13:50 UTC, SeojinSeojin commented on client/src/components/room/monitor/index.style.ts
> +  background-color: #c4c4c4;
매직넘버 발견!!!! 
그치만 여기서만 사용되는 색이라면 슬쩍 넘어가도 될 것 같기도 합니다!

2021-11-26 13:50 UTC, SeojinSeojin commented on client/src/components/room/monitor/index.tsx
>    const myVideoRef = useRef<HTMLVideoElement>(null);
한꺼번에 주는 훅이 있으면 좋을 것 같기도 합니다!
하지만 그동안 이렇게 하신 이유가 있으셨을 터이니 이대로 진행해도 좋을 듯합니다!!

2021-11-26 13:50 UTC, SeojinSeojin commented on client/src/components/user-information/modals/NickChangeModal.tsx
> +    dispatch(setImage(test));
1. `newImage`가 없을 때 요 두 줄 또한 실행되지 않아도 될 것 같습니다 ..!!!

2. 변수 이름이 `test`인 이유는 무엇인가요?

2021-11-26 13:50 UTC, SeojinSeojin commented on client/src/components/user-information/modals/NickChangeModal.tsx
> +        closeModal();
91-93줄, 97-99줄, 103-104줄 내용이 중복됩니다!!

`Promise.all(///)`들을 await한 후 이 부분을 수행하는 방식 또는
```ts
if(!nickChanged && imgChanged) await Promise.all([requestChangeUserImage()]);
else if(nickChanged && !imgChanged) await Promise.all([changeNickname()]);
else if(nickChanged && imgChanged) await Promise.all([changeNickname(), requestChangeUserImage()]);

setNickChanged(false);
setImgChanged(false);
closeModal();
```


이 부분을 하나의 콜백 함수로 묶어서 수행하는 방식 어떠신가요!
```ts
const profileChangeCallback = () => { ... }
```

2021-11-26 13:50 UTC, SeojinSeojin commented on server/src/controller/rank.ts
> +cron.schedule('*/5 * * * *', () => {
크론 넘 멋져요~~~

2021-11-26 13:50 UTC, SeojinSeojin commented on server/src/controller/rank.ts
> +updateAllUserRank();
export를 하셨는데 여기서도 실행하시는 이유는 무엇인가요!!?

2021-11-27 06:10 UTC, yeon52 commented on server/src/controller/rank.ts
> +updateAllUserRank();
앗 ㅠ 원래 저 파일에 있는 getRank를 제외하고는 전부 밖으로 빼야합니다 ㅠㅠ 일단 짜놓고 분리를 한다는 게 깜빡했네요 ..!
그리고 한번 실행하는 이유는, 서버가 실행되면 일단 처음 한번은 저 작업을 해야하기 때문입니다 ! 이것도 app.ts에서 실행을 하는게 맞는것 같아요 !!
짚어주셔서 감사합니다 ㅎㅎ

2021-11-27 06:13 UTC, yeon52 commented on client/src/api/index.ts
> +import { store } from '@src/store/store';
어엇.. 가끔 자동완성을 쓰다보면 저런일이 ㅠㅠ 감사합니다 ! 수정해야겠네용 ㅎㅎ

2021-11-27 12:35 UTC, alittlekitten commented on client/src/components/user-information/modals/NickChangeModal.tsx
> +    dispatch(setImage(test));
앗..... ㅠㅠㅠ 이거 제가 URL값을 API호출로 받아와서 리덕스에 반영하는 과정에서 테스트를 위해 만든 부분이 잘 돌아가서 그냥 그대로 두었더니 발생한 문제같습니다...!!! 세심하게 봐주셔서 정말 감사합니다!!!

2021-11-27 12:37 UTC, alittlekitten requested changes

2021-11-27 12:37 UTC, alittlekitten commented on client/src/components/user-information/modals/NickChangeModal.tsx
> +        closeModal();
무지성 복붙이 여기서 걸려버렸네요 ㅋㅋㅋ큐ㅠㅠㅠ 리팩토링 과정에서 바로 바꾸도록 하겠습니다!!!

2021-11-27 13:22 UTC, superLipbalm reviewed
리뷰 늦어서 죄송합니다... ㅠㅠ
일이 있어서 차안에서 리뷰를 하려다 보니 멀미가 너무 심하네요... 차에서 내린 후 얼른 마저 작성 하겠습니다!

2021-11-27 13:22 UTC, superLipbalm commented on client/src/components/room/monitor/index.tsx
>    const imgUrl = useSelector((state: RootState) => state.user.imgUrl);
여러 곳에서 구독하는 전역 상태의 경우 셀렉터를 커스텀 훅으로 추상화해서 사용하는 것도 좋을 것 같습니다!
```
const useCloseUpUser = () => useSelector((state: RootState) => state.room.closeUpUser);
```
또 같은 유형의 상태들은 묶어서 반환하도록 커스텀 훅을 만들어도 좋을 것 같습니다
```
// useDeviceState.ts
export const useDeviceStatus = () => useSelector((state: RootState) => state.device);

// monitor/index.tsx
const { isVideoOn, isAudioOn, stream } = useDeviceState();
```

2021-11-27 13:22 UTC, superLipbalm commented on client/src/components/room/monitor/index.tsx
> +        </CameraContainer>
MyVideo와 같은 이름을 가진 별도의 하위 컴포넌트로 분리해도 좋을 것 같습니다!

2021-11-27 16:30 UTC, superLipbalm approved these changes
이번주도 정말 깔끔하고 좋은 코드 리뷰 할 수 있어 영광이었습니다!
도움을 드려야 하는데 매번 배워만 가는 것 같네요😅

2021-11-27 16:30 UTC, superLipbalm commented on client/src/components/custom/ErrorToast.tsx
>      dispatch(setNoticeMessage({ errorMessage: '' }));
resetNoticeMessage와 같이 초기값으로 초기화 하는 액션을 별도로 만들어 쓰는 것이 좋아보입니다!
```suggestion
    dispatch(resetNoticeMessage());
```

2021-11-27 16:30 UTC, superLipbalm commented on client/src/components/room/monitor/index.style.ts
>    z-index: ${Z_INDEX.camOn};
z-index 값을 상태에 따라 정해놓고 가져다 쓰는거 너무 좋은 것 같습니다!
저희는 z-index 값이 일관성이 없어서 간혹 의도치 않게 다른 요소를 가려버린다거나 하는 경우가 있었거든요 ㅠㅠ

2021-11-27 16:30 UTC, superLipbalm commented on client/src/components/room/monitor/index.tsx
> +const OtherVideo = ({ className, otherStream, sid }) => {
OtherVideo 컴포넌트를 별도 파일로 분리하는게 좋아 보입니다!
혹 제가 모르는 이유가 있어서 그런거라면... 그대로 두셔도 괜찮습니다😅

2021-11-27 16:30 UTC, superLipbalm commented on server/src/controller/rank.ts
> +cron.schedule('*/5 * * * *', () => {
크론 챌린지 이후로 되게 오랜만에 보네요!
node에서 cron을 돌릴 수 있다니 너무 신기합니다👍

2021-11-27 16:30 UTC, superLipbalm commented on server/src/controller/user.ts
> +  if (!user) throw new CustomError(400, 'id Error');
유효성 검사를 별도 미들 웨어 또는 함수로 분리해서 처리해도 될 것 같습니다!
또 메시지들은 상수로 따로 모아 두고 가져다 쓰면 좋을 것 같아요!

2021-11-27 16:30 UTC, superLipbalm commented on server/src/controller/user.ts
> +export const patchUserNickname = errorWrapper(async (req, res, next) => {
errorWrapper와 CustomError 객체로 에러 핸들링을 하니 깔끔하네요👍👍👍👍👍

2021-11-27 16:30 UTC, superLipbalm commented on server/src/controller/user.ts
> +    message: 'User Information Update Success',
요기 응답 메시지도 위에서 말씀 드린 대로 상수로 빼서 모아두면 좋을 것 같습니다!

2021-11-28 01:39 UTC, Najeong-Kim commented
안녕하세요! 또 뵙겠습니다~! 이번주도 너무 고생하셨어요~~
언제나처럼 읽기 쉽게 작성해주셔서 코드 읽는게 너무 재밌네요!
리뷰하러 왔다가 많이 배우고 가요 ㅎㅎ
근데 저는 왜 그냥 댓글이 아니라 리뷰로 되어있죠 저거 어떻게 못빼나요ㅠㅠ

2021-11-28 04:01 UTC, shinhyogeun approved these changes

2021-11-28 04:01 UTC, shinhyogeun commented on client/src/utils/request.ts
> +      if (body.toString() === '[object FormData]') {
꼭 이렇게 문자열로 비교하는 방법만 있을까요? ㅠㅠ 예전에 저도 이렇게 비교를 했다가 리뷰어님에게 조언을 받은 적이 있어요! 혹시 비교가 어려우시면 별도의 변수로라도 빼는 것이 좋을 것 같아요~!👍

2021-11-28 04:01 UTC, shinhyogeun commented on server/src/controller/rank.ts
> +cron.schedule('*/5 * * * *', () => {
오마이갓.. 오랜만이네요!! ㅋㅋㅋㅋ 대박대박 멋지십니다!

2021-11-28 04:02 UTC, shinhyogeun commented
아주 잘 읽고 가요! 커스텀 에러, 크론탭 등등 많은 것이 재밌네요! 많이 배우고 갑니다! 한주동안 수고 많으셨고 잘 마무리하시길 바랍니다!👍👍

2021-11-28 13:56 UTC, jyo-jyo commented on client/src/components/custom/ErrorToast.tsx
>      dispatch(setNoticeMessage({ errorMessage: '' }));
헉 너무 좋은 것 같습니다!! 다음주에 리팩토링 하면서 적용해보도록 하겠습니다!!

2021-11-28 13:57 UTC, jyo-jyo commented on client/src/components/room/monitor/index.style.ts
>    z-index: ${Z_INDEX.camOn};
저희도 같은 문제를 겪어서 Z-INDEX 서열 정리를 해버렸습니다 ㅋㅋㅋ!!
이렇게 상수화 하니 변경 시에도 용이해서 좋은 것 같습니다!!

2021-11-28 14:00 UTC, jyo-jyo commented on server/src/controller/user.ts
> +  if (!user) throw new CustomError(400, 'id Error');
헉 그러면 코드가 더 깔끔해지겠군요!! 감사합니다 :)
메시지도,.,. 분리,,., (메모)

2021-11-28 14:04 UTC, jyo-jyo commented on client/src/components/room/monitor/index.tsx
>    const imgUrl = useSelector((state: RootState) => state.user.imgUrl);
오 중복되는 전역 상태는 찬희님이 말씀해주신 것처럼 추상화해서 쓰면 좋을 것 같습니다!!
코드까지 작성해주시다니, 감사합니다!!

2021-11-28 17:41 UTC, alittlekitten commented on client/src/components/room/monitor/index.style.ts
> +  background-color: #c4c4c4;
소중한 정보 발견 감사합니다! 상수 제거반 바로 출동하겠습니다.

2021-11-28 17:41 UTC, alittlekitten commented on server/src/controller/rank.ts
> +cron.schedule('*/5 * * * *', () => {
@yeon52 흐-뭇

2021-11-28 17:44 UTC, alittlekitten commented on client/src/components/room/monitor/index.tsx
>    const imgUrl = useSelector((state: RootState) => state.user.imgUrl);
와.. 정말 아무것도 모르고 Redux를 사용하고 있었네요 ㅠㅠ 정말 날카로운 지적 감사합니다 찬희님..!!

2021-11-28 17:45 UTC, alittlekitten commented on client/src/components/custom/ErrorToast.tsx
>      dispatch(setNoticeMessage({ errorMessage: '' }));
항상 '' 형태로 초기화하는 것만 사용했었는데, 생각의 지평을 열어주셨군요..! 감사합니다 :)

2021-11-28 17:47 UTC, alittlekitten commented on client/src/utils/request.ts
> +      if (body.toString() === '[object FormData]') {
우선 냅다 비교를 하다보니 이렇게 작성하게 되었는데, 말씀하신 내용을 듣고 보니 이 부분도 중복될 수 있는 부분이기 때문에 별도로 분리하면 나중에 사용할 때나 수정할 때 도움이 될 것 같습니다 :) 감사합니다!!

2021-11-28 17:48 UTC, alittlekitten commented on client/src/api/index.ts
> +import { store } from '@src/store/store';
src 제거반 출동하겠습니다...!! 감사합니다 ㅎㅎㅎ

2021-11-28 17:52 UTC, alittlekitten commented
> 안녕하세요! 또 뵙겠습니다~! 이번주도 너무 고생하셨어요~~ 언제나처럼 읽기 쉽게 작성해주셔서 코드 읽는게 너무 재밌네요! 리뷰하러 왔다가 많이 배우고 가요 ㅎㅎ 근데 저는 왜 그냥 댓글이 아니라 리뷰로 되어있죠 저거 어떻게 못빼나요ㅠㅠ

이거 저희가 설정해놓은거라서 그런가봐요 ㅎㅎㅎㅎ 리뷰는 필수가 아니니 걱정하지 않으셔도 됩니다 :)

2021-11-30 01:28 UTC, closed without merging